// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Oid85.FinMarket.StatArbitrage.Infrastructure.Database;

#nullable disable

namespace Oid85.FinMarket.Algo.Infrastructure.Migrations
{
    [DbContext(typeof(StatArbitrageContext))]
    [Migration("20260706154742_06072026_4")]
    partial class _06072026_4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityAlwaysColumns(modelBuilder);

            modelBuilder.Entity("Oid85.FinMarket.Algo.Infrastructure.Database.Entities.StrategyExecuteResultEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AnnualYieldReturn")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageNetProfit")
                        .HasColumnType("double precision");

                    b.Property<double>("AverageNetProfitPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("CurrentPosition")
                        .HasColumnType("integer");

                    b.Property<double>("CurrentPositionCost")
                        .HasColumnType("double precision");

                    b.Property<double>("Drawdown")
                        .HasColumnType("double precision");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<double>("EndMoney")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxDrawdown")
                        .HasColumnType("double precision");

                    b.Property<double>("MaxDrawdownPercent")
                        .HasColumnType("double precision");

                    b.Property<int>("NumberPositions")
                        .HasColumnType("integer");

                    b.Property<string>("PortfolioName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ProfitFactor")
                        .HasColumnType("double precision");

                    b.Property<double>("RecoveryFactor")
                        .HasColumnType("double precision");

                    b.Property<string>("ResultMessage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<double>("StartMoney")
                        .HasColumnType("double precision");

                    b.Property<string>("StrategyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyParams")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StrategyParamsHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalNetProfit")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalReturn")
                        .HasColumnType("double precision");

                    b.Property<int>("WinningPositions")
                        .HasColumnType("integer");

                    b.Property<double>("WinningTradesPercent")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("StrategyExecuteResultEntities", "public");
                });
#pragma warning restore 612, 618
        }
    }
}
