<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Accord.Math" />
	  <PackageReference Include="Accord.Statistics" />
	  <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
	  <PackageReference Include="Microsoft.Extensions.Options" />
	  <PackageReference Include="NLog" />
	  <PackageReference Include="Skender.Stock.Indicators" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Oid85.FinMarket.StatArbitrage.Common\Oid85.FinMarket.StatArbitrage.Common.csproj" />
    <ProjectReference Include="..\Oid85.FinMarket.StatArbitrage.Core\Oid85.FinMarket.StatArbitrage.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Factories\" />
    <Folder Include="Interfaces\Factories\" />
    <Folder Include="Strategies\" />
  </ItemGroup>

</Project>
